In [30]:
import numpy as np

In [31]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
np.random.rand(2,3)

array([[0.36262109, 0.01997232, 0.5850629 ],
       [0.9400373 , 0.6578577 , 0.68265617]])

In [34]:
a = 8+98+56+20
a

182

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
rand_array = np.random.randint(0,80,20)
rand_array

array([53, 24, 79, 63,  9, 16,  7, 62,  1, 45, 65, 17, 69, 22, 52, 65,  6,
       45, 72, 17])

In [38]:
rand_array.max()

79

In [58]:
b = rand_array.reshape(5,4)
b

array([[53, 24, 79, 63],
       [ 9, 16,  7, 62],
       [ 1, 45, 65, 17],
       [69, 22, 52, 65],
       [ 6, 45, 72, 17]])

In [40]:
rand_array.argmax()

2

In [41]:
rand_array.dtype


dtype('int32')

In [42]:
b = np.eye(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
b = np.random.rand(2,4

array([[0.05858266, 0.49157366, 0.68129757, 0.47131994],
       [0.85718247, 0.51387154, 0.84145271, 0.91023525]])

In [52]:
b.max()

0.9102352453559527

In [53]:
b.min()

0.05858266487157071

# 2-dimensional arrays

In [66]:
matrix = np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [70]:
matrix[1][3]

33

In [ ]:
matrix

In [71]:
matrix[:,2]

array([ 1, 21, 24])

In [69]:
matrix[1:3,1:3]

array([[23, 21],
       [76, 24]])

In [72]:
matrix[0:3,(2,3)]

array([[ 1, 23],
       [21, 33],
       [24,  7]])

In [73]:
np.square(matrix)

array([[2500,  400,    1,  529],
       [ 576,  529,  441, 1089],
       [3136, 5776,  576,   49]], dtype=int32)

In [61]:
array = np.arange(1,14)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [58]:
m = np.mean(array)
m

2.5

In [73]:
import statistics as stats
a = [2,3,2,2,4,5,5,5,5,5]
m2 = stats.mode(a)
m2

5

In [75]:
arr = [1,11,121,24,16]
print(np.var(arr))

1921.8400000000001


In [62]:
m1 = np.median(array)
m1

7.0

# selection technique

In [78]:
bool = array<8
bool

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False])

In [79]:
np.exp(array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05])

In [80]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128])

In [81]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936])

In [83]:
np.argmax(array)

12

In [84]:
languages = np.array(['hindi','telugu','eng','hindi','telugu'])
np.unique(languages)

array(['eng', 'hindi', 'telugu'], dtype='<U6')

In [11]:
import numpy as np

# pandas dataframe and indexing 

In [1]:
import pandas as pd

In [4]:
labels = ['w','x','y','z']

In [5]:
list = [10,20,30,40]

In [14]:
array = np.array([1,2,3,4])

In [18]:
dict = {'w':10,'x':20,'y':30,'z':40}

In [7]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [8]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [15]:
pd.Series(labels,array)

1    w
2    x
3    y
4    z
dtype: object

In [19]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [21]:
sports1 = pd.Series([1,2,3,4],index = ['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [25]:
sports1['cricket']

1

In [22]:
sports2 = pd.Series([11,2,33,4],index = ['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball    33
golf         4
dtype: int64

In [24]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [45]:
df1 = pd.DataFrame(np.random.rand(7,5),index = 'A B C D E F G'.split(),columns = 'score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.362758  0.919948  0.378590  0.148253  0.873984
B  0.665496  0.681448  0.184255  0.054842  0.699426
C  0.690708  0.332263  0.033669  0.951041  0.626746
D  0.695982  0.363613  0.261349  0.323443  0.934228
E  0.440191  0.470261  0.551792  0.772008  0.618766
F  0.980270  0.572350  0.424561  0.349946  0.509115
G  0.419271  0.642475  0.882744  0.264336  0.915917

In [49]:
df1['score6'] = df1['score1']+df1['score2']
df1

score1    score2    score3    score4    score5    score6
A  0.362758  0.919948  0.378590  0.148253  0.873984  1.282705
B  0.665496  0.681448  0.184255  0.054842  0.699426  1.346944
C  0.690708  0.332263  0.033669  0.951041  0.626746  1.022971
D  0.695982  0.363613  0.261349  0.323443  0.934228  1.059595
E  0.440191  0.470261  0.551792  0.772008  0.618766  0.910452
F  0.980270  0.572350  0.424561  0.349946  0.509115  1.552620
G  0.419271  0.642475  0.882744  0.264336  0.915917  1.061746

In [50]:
df1.drop('score4',axis=1)

score1    score2    score3    score5    score6
A  0.362758  0.919948  0.378590  0.873984  1.282705
B  0.665496  0.681448  0.184255  0.699426  1.346944
C  0.690708  0.332263  0.033669  0.626746  1.022971
D  0.695982  0.363613  0.261349  0.934228  1.059595
E  0.440191  0.470261  0.551792  0.618766  0.910452
F  0.980270  0.572350  0.424561  0.509115  1.552620
G  0.419271  0.642475  0.882744  0.915917  1.061746

In [51]:
df1.drop('E')

score1    score2    score3    score4    score5    score6
A  0.362758  0.919948  0.378590  0.148253  0.873984  1.282705
B  0.665496  0.681448  0.184255  0.054842  0.699426  1.346944
C  0.690708  0.332263  0.033669  0.951041  0.626746  1.022971
D  0.695982  0.363613  0.261349  0.323443  0.934228  1.059595
F  0.980270  0.572350  0.424561  0.349946  0.509115  1.552620
G  0.419271  0.642475  0.882744  0.264336  0.915917  1.061746

In [55]:
df1.reset_index()

index    score1    score2    score3    score4    score5    score6
0     A  0.362758  0.919948  0.378590  0.148253  0.873984  1.282705
1     B  0.665496  0.681448  0.184255  0.054842  0.699426  1.346944
2     C  0.690708  0.332263  0.033669  0.951041  0.626746  1.022971
3     D  0.695982  0.363613  0.261349  0.323443  0.934228  1.059595
4     E  0.440191  0.470261  0.551792  0.772008  0.618766  0.910452
5     F  0.980270  0.572350  0.424561  0.349946  0.509115  1.552620
6     G  0.419271  0.642475  0.882744  0.264336  0.915917  1.061746

In [54]:
df2 = {'id':[101,102,103,104,105],'name':['j','a','c','k','y'],'profit':[10,20,30,40,50,]}
df = pd.DataFrame(df2)
df

id name  profit
0  101    j      10
1  102    a      20
2  103    c      30
3  104    k      40
4  105    y      50